### PR TITLE
Add alerting for clamav daily updates

### PR DESCRIPTION
**Pull request by brenetic**
This adds the ability for us to be alerted if the updates that freshclam does daily for the bytecode, main and daily definitions fail.

We also bumped Debian image to Buster.

We needed to inject the Sentry DSN and therefore also changed how the deployment script works. 

https://trello.com/c/F4pFxQuD/631-add-alerting-to-fb-anti-virus

Co-authored-by Tomas Destefi <tomas.destefi@digital.justice.gov.uk>

### CODE REVIEW

**Review by tomas-stefano — DISMISSED** [review]
🚀 🎸

**Review by tomas-stefano — DISMISSED** [review]
🎸 🚀

**Review by mattempty — DISMISSED** [review]
🚀

**Review by tomas-stefano — APPROVED** [review]
🚀 🎸

**Pull request merged**
